"""Primeira migration limpa

Revision ID: 7644b3b3f491
Revises: 
Create Date: 2026-02-02 22:34:44.399913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7644b3b3f491'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', sa.Float(), nullable=False, server_default='0.0'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('valor')

    # ### end Alembic commands ###
