"""cria tabela produtos

Revision ID: ebedec45a5cb
Revises: 
Create Date: 2026-02-04 22:58:03.883964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebedec45a5cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamentos',
    sa.Column('id', sa.String(length=4), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('arquivo_imagem', sa.String(length=500), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto_cores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=50), nullable=False),
    sa.Column('imagem', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_cores')
    op.drop_table('produtos')
    op.drop_table('orcamentos')
    # ### end Alembic commands ###
